# Database configuration.
# Used for saving placed generators and doubledrop values.
database:
  # Available types: mysql, sqlite
  type: 'sqlite'
  # Table names used both in mysql or sqlite
  generators-table: 'ygene_generators'
  doubledrop-table: 'ygene_doubledrop'

  # Path for SQLite database file
  path: 'database.db'

  # Connection info for MySQL database type
  # Host of your db
  host: 'localhost'
  # Default is 3306, don't touch it if you didn't change it in your db configuration
  port: '3306'
  # Default: 6
  max-connections: 6
  # Name of database
  name: 'dbname'
  # Login to db account
  login: 'user'
  # Password to db account
  password: 'password'

  # Database update interval in seconds
  update-interval: 60

# General generators configuration
generators:
  # Max amount of generators that can be placed in a single chunk.
  # Set to -1 to disable this feature
  max-in-chunk: 20

  # Worlds in which generators will be disabled
  disabled-worlds:
    - example_world
    - example_world_2

  # Durability list at which alerts will be sent to a player about low generator durability
  alert-durability:
    - 1
    - 2
    - 5
    - 10
    - 20
    - 50

  # Whether generators can be placed on top of each other
  place-on-top: false

  # Actions to pick up a generator
  pick-up:
    # Whether this feature should be enabled
    enabled: true
    # If a player must be sneaking to pick up the generator
    sneak: true
    # If the player must have an empty hand
    empty-hand: true
    # What button the player must use to pick up the generator
    # Available buttons: left, right
    click: right

  # Actions to check status of the placed generator
  # When enabled, player can click on the generator to get its status on the action bar
  check-status:
    # Whether this feature should be enabled
    enabled: true
    # If the player must be sneaking to check the generator's status
    sneak: true
    # If the player must have an empty hand
    empty-hand: true
    # What button the player must use
    # Available buttons: left, right
    click: left


# Options to change vanilla generators (those water-lava ones)
vanilla-generators:
  # Whether plugin should change default vanilla generators behavior
  enabled: false

  # Whether block chances should be multiplied by double drop multiplayer
  # when double drop is active
  use-doubledrop: true

  # Default block to generate
  # Use 'default' to not change the default block generated by vanilla
  default-block: default

  # Blocks to generate, format:
  # <material>: <chance>
  blocks:
    DIAMOND_ORE: 0.05
    EMERALD_ORE: 0.10
    GOLD_ORE: 0.20
    COPPER_ORE: 0.30
    IRON_ORE: 0.35
    REDSTONE_ORE: 0.45
    LAPIS_ORE: 0.45
    COAL_ORE: 0.60
    STONE: 2.0

# Other additional options
other-options:
  # Whether iron, gold and copper ores should drop itself and not a raw ore
  1-16-ores: false