name: '${project.name}'
version: '${project.version}'
main: pl.ynfuien.ygenerators.YGenerators
api-version: '1.20'
softdepend: [ PlaceholderAPI ]
loadbefore: [ SuperiorSkyblock2 ]
authors: [ Ynfuien ]
description: '${project.description}'
website: '${project.url}'

commands:
  ygenerators:
    description: Admin command with reload and give subcommands
    permission: ygenerators.admin
    aliases: [ ygene ]

  doubledrop:
    description: Checks time left of the double drop
    permission: ygenerators.doubledrop
    aliases: [ dd ]

permissions:
  ygenerators.doubledrop:
    default: true
