name: Bug Report
description: Report found bug
assignees: [Ynfuien]
labels: ["Bug Report", "On fly"]
body:
  - type: input
    attributes:
      label: Server version
      description: Version and type of your server
      placeholder: Paper 1.18.2
    validations:
      required: true

  - type: input
    attributes:
      label: Plugin version
      description: Plugin version that you use (not "latest")
      placeholder: 1.0.0
    validations:
      required: true

  - type: textarea
    attributes:
      label: Description
      description: All informations about what is not working or is working incorrectly
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional info
      description: Any additional info or screenshots
    validations:
      required: false